language: ruby
rvm:
 - "2.0.0"
 - "2.2.1"
script: bundle exec rspec spec
addons:
    code_climate:
        repo_token: 69a832cbd11706e0578a20c2aae40d42cf520f3a9a776932bc32833dd1b58f2b
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - andrew@topdog.za.net
